NAME =	PhoneBook
CXX = c++
CXXFLAGS += -Wall -Wextra -Werror -std=c++98 -g3

SRC =	./src/PhoneBook.cpp \
		./src/Contact.cpp \
		main.cpp

OBJ = $(SRC:.cpp=.o)

.phony: all re clean fclean

all:		$(NAME)

$(NAME):	$(OBJ)
			$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

%.o:		%.cpp
			$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
			rm -f $(OBJ)

fclean:		clean
			rm -f $(NAME)

re:			fclean all

